version: "2"

services:
  # postgres:
  #   mem_limit: 512m
  #   image: postgres:9.5
  #   volumes:
  #     - /var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #   restart: always
  cachet:
    mem_limit: 512m
    image: ${REGISTRY}/cachet:${TAG}
    build:
      context: .
      args:
        - cachet_ver=master
    ports:
      - 80:8000
    # links:
    #   - postgres:postgres
    environment:
      - DB_DRIVER=pgsql
      - DB_HOST
      - DB_PORT
      - DB_DATABASE
      - DB_USERNAME
      - DB_PASSWORD
      - DB_PREFIX=chq_
      - APP_KEY=UyIXoUsiAzvWrnfZwp1DAC50SQHuH5b2
      - APP_LOG=errorlog
      - DEBUG=false
    # depends_on:
    #   - postgres
    restart: on-failure
